version: '3.9'
services:
  telegram-bot:
    build: 
      context: ./
      dockerfile: Dockerfile
    environment:
      AWS_SECRET_KEY: "${AWS_SECRET_KEY}"
      AWS_ACCESS_ID: "${AWS_ACCESS_ID}"
      OPEN_AI_SECRET_KEY: "${OPEN_AI_SECRET_KEY}"
      TELEGRAM_BOT_TOKEN: "${TELEGRAM_BOT_TOKEN}"
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local