version: '3.9'
services:
  telegram-bot:
    build: 
      context: ./
      dockerfile: Dockerfile
    environment:
      AWS_SECRET_KEY: "${AWS_SECRET_KEY}"
      AWS_ACCESS_ID: "${AWS_ACCESS_ID}"
      OPEN_AI_SECRET_KEY: "${OPEN_AI_SECRET_KEY}"
      AWS_REGION: "${AWS_REGION}"
      TELEGRAM_BOT_TOKEN: "${TELEGRAM_BOT_TOKEN}"
      DB_NAME: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD:  "postgres"
    links:
      - db
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql

volumes:
  db:
    driver: local